In [41]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Input, SimpleRNN, GRU, LSTM, Bidirectional, Embedding

In [7]:
rnn = Sequential([
    Input((10, 4)),
    SimpleRNN(64, activation  = "relu")
])

In [8]:
rnn.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 simple_rnn_2 (SimpleRNN)    (None, 64)                4416      
                                                                 
Total params: 4,416
Trainable params: 4,416
Non-trainable params: 0
_________________________________________________________________


In [22]:
rnn2 = Sequential([
    Input((10, 4)),
    SimpleRNN(64, activation  = "relu", return_sequences = True),
    SimpleRNN(32, activation  = "relu", return_sequences = True),
    SimpleRNN(16, activation  = "relu", return_sequences = True),
    SimpleRNN(8, activation  = "relu")
])

In [23]:
rnn2.summary()

Model: "sequential_5"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 simple_rnn_10 (SimpleRNN)   (None, 10, 64)            4416      
                                                                 
 simple_rnn_11 (SimpleRNN)   (None, 10, 32)            3104      
                                                                 
 simple_rnn_12 (SimpleRNN)   (None, 10, 16)            784       
                                                                 
 simple_rnn_13 (SimpleRNN)   (None, 8)                 200       
                                                                 
Total params: 8,504
Trainable params: 8,504
Non-trainable params: 0
_________________________________________________________________


In [15]:
rnn3_layer1 = SimpleRNN(64, return_sequences = True, return_state = True)

In [18]:
data = np.random.normal(size = (16, 10, 4))
# steps, variables, 

In [19]:
rnn3_layer1(data)

[<tf.Tensor: shape=(16, 10, 64), dtype=float32, numpy=
 array([[[-0.06532398, -0.05810557,  0.19030093, ..., -0.01456565,
           0.03920301,  0.4835705 ],
         [ 0.5687352 , -0.30775076,  0.17016338, ...,  0.30640963,
          -0.70588493, -0.46529058],
         [-0.02913049,  0.7201563 ,  0.64132524, ..., -0.58490825,
          -0.41690785,  0.3156782 ],
         ...,
         [-0.6847788 ,  0.04005945,  0.6918271 , ..., -0.7526107 ,
          -0.33546674, -0.7507666 ],
         [-0.7990683 , -0.44692868, -0.21341692, ...,  0.10901958,
           0.7562435 ,  0.38238305],
         [-0.04290424, -0.08277518,  0.4126016 , ..., -0.01137064,
           0.33054623,  0.25747448]],
 
        [[-0.11057088, -0.13304606,  0.12079915, ..., -0.00432236,
          -0.08912548,  0.135906  ],
         [ 0.8807096 , -0.14831896, -0.2955724 , ...,  0.5497358 ,
          -0.0330222 , -0.2767284 ],
         [ 0.595951  , -0.4590593 ,  0.4510797 , ..., -0.45476374,
          -0.6547944 , -0.467

In [25]:
x = np.random.normal(size = (16, 10, 4))
# batch size, time steps, variables

In [26]:
rnn2.predict(x)

array([[0.3401082 , 0.22542737, 0.08438864, 0.16208813, 0.        ,
        0.5166507 , 0.        , 0.1268729 ],
       [0.        , 0.1375774 , 0.4630014 , 0.41140172, 0.        ,
        0.22481415, 0.        , 0.        ],
       [0.5441092 , 0.        , 1.0274831 , 0.82794803, 0.        ,
        0.        , 0.        , 0.2869411 ],
       [0.62194526, 0.08886561, 0.03928444, 0.10085015, 0.        ,
        0.05448556, 0.        , 0.4482446 ],
       [0.1388034 , 0.01088637, 0.11562759, 0.14251307, 0.        ,
        0.7267194 , 0.        , 0.        ],
       [0.10961133, 0.1940727 , 0.2951361 , 0.38154066, 0.        ,
        0.2690384 , 0.11290035, 0.36766946],
       [0.2674029 , 0.        , 0.2095564 , 0.30517784, 0.        ,
        0.36903244, 0.        , 0.25840703],
       [0.7165885 , 0.5639709 , 0.6609867 , 0.17306194, 0.        ,
        0.27882466, 0.        , 0.47619474],
       [0.29646912, 0.        , 0.16834001, 0.59909153, 0.11998962,
        0.08220971, 0.      

In [27]:
rnn2.predict(x).shape

(16, 8)

In [29]:
rnn2.predict(x)[0] # first sample

array([0.3401082 , 0.22542737, 0.08438864, 0.16208813, 0.        ,
       0.5166507 , 0.        , 0.1268729 ], dtype=float32)

In [33]:
gru = GRU(64, return_sequences = True, return_state = True)

In [34]:
gru(x)

[<tf.Tensor: shape=(16, 10, 64), dtype=float32, numpy=
 array([[[-0.00213465, -0.01808017, -0.02695779, ...,  0.02834189,
           0.01589131,  0.06356727],
         [ 0.00029919, -0.02640589,  0.04205329, ..., -0.00828133,
          -0.00336965, -0.01011924],
         [-0.1006368 ,  0.14039205, -0.04183628, ...,  0.02938236,
          -0.03895453, -0.06474994],
         ...,
         [ 0.01957642, -0.00103381, -0.03736681, ..., -0.1348305 ,
          -0.03373634, -0.11756691],
         [-0.17514157,  0.16779903,  0.01467467, ...,  0.20657718,
          -0.07210222, -0.022672  ],
         [-0.07387082, -0.10175827,  0.0479712 , ..., -0.10149594,
          -0.02401397, -0.14532544]],
 
        [[-0.02222935,  0.12487374, -0.13863146, ...,  0.10914349,
           0.0166954 ,  0.17174782],
         [ 0.02296122,  0.11231555, -0.10230935, ..., -0.0040185 ,
           0.00789654,  0.03505372],
         [-0.01050266,  0.00199502,  0.06813346, ...,  0.02070378,
          -0.01014769, -0.055

In [35]:
lstm = LSTM(64, return_sequences = True, return_state = True)

In [36]:
lstm(x)

[<tf.Tensor: shape=(16, 10, 64), dtype=float32, numpy=
 array([[[-0.00808366, -0.02491725,  0.01294041, ..., -0.01085905,
          -0.00889657, -0.00310304],
         [ 0.00032295,  0.01016319,  0.01126023, ...,  0.01329921,
          -0.00157602, -0.00947394],
         [ 0.03607395,  0.03539491, -0.05384002, ..., -0.04399928,
          -0.02338282,  0.03871839],
         ...,
         [ 0.00559593,  0.01230644, -0.00686457, ...,  0.05222547,
           0.03697014,  0.01938259],
         [ 0.09103241,  0.08238864, -0.06892659, ..., -0.03087617,
          -0.0518513 ,  0.04465212],
         [ 0.0915408 ,  0.10459499, -0.00609464, ...,  0.04235046,
          -0.0038656 ,  0.00695703]],
 
        [[-0.02131006, -0.07732373, -0.02711751, ..., -0.09263879,
          -0.02001886,  0.03113827],
         [-0.0367116 , -0.07450332, -0.03901041, ..., -0.05772586,
           0.00617182,  0.04887157],
         [ 0.0097407 ,  0.02230897, -0.02217905, ..., -0.0022341 ,
          -0.00926121,  0.013

In [37]:
lstm.weights[0].shape

TensorShape([4, 256])

In [39]:
bidirectional = Bidirectional(LSTM(64))

In [40]:
bidirectional(x)

<tf.Tensor: shape=(16, 128), dtype=float32, numpy=
array([[ 0.00817883,  0.05050353,  0.09217387, ...,  0.00589207,
        -0.06511257,  0.01136211],
       [-0.03545505, -0.01065368, -0.04280177, ...,  0.0344828 ,
        -0.12822144,  0.068075  ],
       [ 0.03502763,  0.06504878,  0.02121772, ...,  0.0198219 ,
        -0.10812231,  0.0308398 ],
       ...,
       [ 0.01725266, -0.00031984,  0.01206602, ..., -0.06697213,
        -0.01746143, -0.05275025],
       [-0.0648874 , -0.01378255,  0.10647972, ..., -0.03881293,
         0.03185516, -0.06036908],
       [-0.02082562,  0.00679044,  0.00145065, ...,  0.02659761,
         0.03627623, -0.009247  ]], dtype=float32)>

In [43]:
lstm_with_embedding = Sequential([
    Embedding(10000, 400),
    LSTM(64)
])

In [44]:
lstm_with_embedding.summary()

Model: "sequential_6"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, None, 400)         4000000   
                                                                 
 lstm_2 (LSTM)               (None, 64)                119040    
                                                                 
Total params: 4,119,040
Trainable params: 4,119,040
Non-trainable params: 0
_________________________________________________________________


In [45]:
tf.keras.preprocessing.text.Tokenizer()