In [1]:
%matplotlib inline

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

import tensorflow as tf

# Live Demos

In [3]:
# check if it works
tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU')]

In [4]:
# (2a + 3b) ** 2
def compute (a, b):
    return tf.pow(tf.add(tf.multiply(2, a), tf.multiply(3, b)), 2)

In [5]:
a = tf.constant(5)
b = tf.constant(10)

In [6]:
compute(a, b)

<tf.Tensor: shape=(), dtype=int32, numpy=1600>

In [7]:
type(compute(a, b))

tensorflow.python.framework.ops.EagerTensor

In [8]:
compute(a, b).numpy()

1600

In [9]:
type(compute(a, b).numpy())

numpy.int32

In [10]:
compute([1, 2, 3, 5], [4, 5, 6, 10])

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([ 196,  361,  576, 1600])>

In [11]:
compute(np.array([1, 2, 3, 5]), np.array([4, 5, 6, 10]))

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([ 196,  361,  576, 1600])>

In [12]:
compute(5, 10)

<tf.Tensor: shape=(), dtype=int32, numpy=1600>

In [13]:
@ tf.function
def compute(a, b):
    return(2 * a + 3 * b) ** 2

In [14]:
compute(2, 3)

<tf.Tensor: shape=(), dtype=int32, numpy=169>

In [15]:
type(compute(2, 3))

tensorflow.python.framework.ops.EagerTensor

In [16]:
compute(a, b)

<tf.Tensor: shape=(), dtype=int32, numpy=1600>

In [17]:
compute(np.array([1, 2, 3, 5]), np.array([4, 5, 6, 10]))

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([ 196,  361,  576, 1600])>

In [19]:
writer = tf.summary.create_file_writer("logs")
a, b = tf.constant([2, 3, 4], tf.constant([3, 4, 5])
tf.summary.trace_on(graph = True, profiler = True)
result = compute(a, b)
print(result.numpy())
with writer.as_default():
    tf.summary.trace_export(name = "compute_trace", step = 0, profiler_outdir = "logs")

SyntaxError: invalid syntax (<ipython-input-19-32c52175a82f>, line 4)